version: '3'
services:
  tzpay:
     image: goatsystems/tzpay:v3.0.0 
     container_name: tzpay
     restart: always
     command: tzpay serv
     environment:
        # Required
        - TZPAY_BAKER=TODO
        - TZPAY_BAKER_FEE=TODO
        - TZPAY_WALLET_ESK=TODO
        - TZPAY_WALLET_PASSWORD=TODO
        # Optional
        - TZPAY_BAKER_LIQUIDITY_CONTRACTS_ONLY=<TODO (e.g. True)>
        - TZPAY_BAKER_MINIMUM_PAYMENT=<TODO (e.g. MUTEZ 10000)>
        - TZPAY_BAKER_EARNINGS_ONLY=<TODO (e.g. True)>
        - TZPAY_BAKER_BLACK_LIST=<TODO (e.g. KT19Aro5JcjKH7J7RA6sCRihPiBQzQED3oQC, KT1CQiyDJ3mMVDoEqLY8Fz1onFXo5ycp5BDN)>
        - TZPAY_BAKER_LIQUIDITY_CONTRACTS=<TODO (e.g. KT19Aro5JcjKH7J7RA6sCRihPiBQzQED3oQC, KT1CQiyDJ3mMVDoEqLY8Fz1onFXo5ycp5BDN)>
        - TZPAY_API_TZKT=<TODO (e.g. https://api.tzkt.io )>
        - TZPAY_API_TEZOS=<TODO (e.g. https://tezos.giganode.io/)>
        - TZPAY_OPERATIONS_NETWORK_FEE=<TODO (e.g. 2941)>
        - TZPAY_OPERATIONS_GAS_LIMIT=<TODO (e.g. 26283)>
        - TZPAY_OPERATIONS_BATCH_SIZE=<TODO (e.g. 125)>
